sudo: false
language: ruby
rvm:
  - 2.2.3
cache: bundler
before_install: gem install bundler
before_script:
  - git config --global user.email "cyrus@redblock.com"
  - git config --global user.name "Cyrus Redblock"
branches:
  only:
    - master
bundler_args: --retry=6
script:
  - bundle exec rake
